Added keypairs, some lines to install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,9 @@
 current_date_time=$(date)
 rc_file=$1
 tag_name=$2
+publickey=$3
 echo "$current_date_time Starting deployment of $tag_name using $rc_file for credentials."
+source $rc_file
 
 # creating network
 # check if network already exists
@@ -12,20 +14,40 @@ echo "$current_date_time Starting deployment of $tag_name using $rc_file for cre
 
 network_name="$2_network"
 subnet_name="$2_subnet"
+keypair_name="$2_keypair"
+
+# Check if keypair exists
+existing_keypairs=$(openstack keypair list -f value --column Name)
+
+if echo "$existing_keypairs" | grep -qFx $keypair_name; then
+    echo "$(date) Skipping keypai creation as $keypair_name already exists"
+else
+    # Create Keypair
+    created_keypair=$(openstack keypair create --public-key $publickey "$keypair_name" )
+
+    if [ $? -eq 0 ]; then
+        echo "$(date) Created keypair $keypair_name"
+    else
+        echo "$(date) !! Failed to create keypair"
+        exit 1
+    fi
+fi
+    
+
 
 # Check if network already exists
 existing_networks=$(openstack network list --tag "$tag_name" --column Name -f value)
 
 if echo "$existing_networks" | grep -qFx $network_name; then
-    echo "Skipping network creation as $network_name already exists"
+    echo "$(date) Skipping network creation as $network_name already exists"
 else
     # Create network
     created_network=$(openstack network create --tag "$tag_name" "$network_name" -f json)
 
     if [ $? -eq 0 ] && [ "$(jq -r '.admin_state_up' <<< "$created_network")" = "true" ]; then
-        echo "Created network $network_name"
+        echo "$(date) Created network $network_name"
     else
-        echo "!! Failed to create network"
+        echo "$(date) !! Failed to create network"
         exit 1
     fi
 fi
@@ -34,15 +56,15 @@ fi
 existing_subnets=$(openstack subnet list --tag "$tag_name" --column Name -f value)
 
 if echo "$existing_subnets" | grep -qFx $subnet_name; then
-    echo "Skipping subnet creation as $subnet_name already exists"
+    echo "$(date) Skipping subnet creation as $subnet_name already exists"
 else
     # Create network
     created_subnet=$(openstack subnet create --subnet-range 10.10.0.0/24 --allocation-pool start=10.10.0.2,end=10.10.0.30 --tag "$tag_name" --network "$network_name" "$subnet_name" -f json)
 
     if [ $? -eq 0 ]; then #&& [ "$(jq '.cidr' <<< "$created_subnet")" == "\"10.10"" ]
-        echo "Created subnet $subnet_name"
+        echo "$(date) Created subnet $subnet_name"
     else
-        echo "!! Failed to create subnet"
+        echo "$(date) !! Failed to create subnet"
         exit 1
     fi
 fi
